server:
  port: 8761

spring:
  application:
    name: discovey-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    renewal-percent-threshold: 0.85

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF